# Generated by Django 3.2 on 2021-10-09 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211009_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quesmodel1',
            old_name='question',
            new_name='question1',
        ),
        migrations.RenameField(
            model_name='quesmodel2',
            old_name='question',
            new_name='question2',
        ),
        migrations.RenameField(
            model_name='quesmodel3',
            old_name='question',
            new_name='question3',
        ),
        migrations.RenameField(
            model_name='quesmodel4',
            old_name='question',
            new_name='question4',
        ),
        migrations.RenameField(
            model_name='quesmodel5',
            old_name='question',
            new_name='question5',
        ),
    ]
