# Generated by Django 3.2 on 2021-10-10 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20211009_1733'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuesModel3',
        ),
        migrations.DeleteModel(
            name='QuesModel4',
        ),
        migrations.DeleteModel(
            name='QuesModel5',
        ),
    ]
