# Generated by Django 4.1.1 on 2022-11-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ans',
            field=models.CharField(default='', max_length=355),
        ),
        migrations.AddField(
            model_name='profile',
            name='ques',
            field=models.CharField(default='', max_length=255),
        ),
    ]
