# Generated by Django 4.1.1 on 2022-11-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_profile_ans_alter_profile_ques'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ans',
            field=models.CharField(max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ques',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
