# Generated by Django 4.1.1 on 2022-11-08 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_remove_userdata_ans_remove_userdata_ques_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userdata',
        ),
    ]
