# Generated by Django 4.1.1 on 2022-11-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_delete_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=255)),
                ('correct', models.CharField(default='', max_length=255)),
                ('wrong', models.CharField(default='', max_length=255)),
                ('percent', models.CharField(default='', max_length=255)),
                ('total', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
