# Generated by Django 4.1.1 on 2022-11-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
